owner: IJPNY
repo: upptime

sites:
  - name: Pilsudski Institute
    url: https://pilsudski.org
  - name: Pilsudski Archiwa Online
    url: http://archiwa.pilsudski.org
  - name: Pilsudski Katalog Biblioteki
    url: http://www.pilsudskilibrary.org
  - name: Powstania Śląskie
    url: https://powstania.pilsudski.org

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Piłsudski Institute Sites Monitor**"
  introMessage: Status updated every hour
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - klinga

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* */1 * * *"
